#!/usr/local/bin/bash

usage() {
    echo "Emojify your text ¯\_(ツ)_/¯"
    echo
    echo "Usage: 'YOUR_TEXT' EMOJI_ONE EMOJI_TWO"
    echo
    echo "  YOUR_TEXT must be surrounded by single quotes"
    echo "   -t  --text_emoji"
    echo "              Emoji for creating characters."
    echo "   -s  --space_emoji"
    echo "              Emoji for spaces between characters."
    echo "  --help  Output this help."
}

# if [ $# -ne 3 ]; then
#     usage
#     exit 1
# fi

YOUR_TEXT=$1
COLOR=":$2:"
SPACE=":$3:"

# Create an associative array of alphabet emoji conversions
declare -A ALPHABET
ALPHABET["a"]="$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE"
ALPHABET["b"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE"
ALPHABET["c"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["d"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE"
ALPHABET["e"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["f"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE"
ALPHABET["g"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE$SPACE\n$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$COLOR$SPACE"
ALPHABET["h"]="$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE"
ALPHABET["i"]="$COLOR$COLOR$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["j"]="$SPACE$SPACE$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE"
ALPHABET["k"]="$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE"
ALPHABET["l"]="$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["m"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE"
ALPHABET["n"]="$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE"
ALPHABET["o"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["p"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE"
ALPHABET["q"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE\n$SPACE$SPACE$COLOR$COLOR$SPACE"
ALPHABET["r"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE"
ALPHABET["s"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["t"]="$COLOR$COLOR$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE"
ALPHABET["u"]="$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["v"]="$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE"
ALPHABET["w"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE"
ALPHABET["x"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$COLOR$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE\n$SPACE$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE"
ALPHABET["y"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$COLOR$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE"
ALPHABET["z"]="$COLOR$COLOR$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["."]="$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$COLOR$SPACE"
ALPHABET[","]="$SPACE$SPACE$SPACE\n$SPACE$SPACE$SPACE\n$SPACE$SPACE$SPACE\n$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE"
ALPHABET["'"]="$COLOR$SPACE\n$COLOR$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE"
ALPHABET[" "]="$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE"

LOWER=${YOUR_TEXT,,}
# echo "Paste this in slack \(^_^)/"
# echo "==========================="
for i in $(seq 0 $((${#LOWER} - 1))); do
	printf "${ALPHABET[${LOWER:$i:1}]}\n\n"
done
# echo "==========================="
