#!/usr/local/bin/bash

#
# Usage statement
#
usage() {
    echo "Emojify your text ¯\_(ツ)_/¯"
    echo
    echo "Usage: $0 -t 'YOUR_TEXT' -e EMOJI..."
    echo
    echo "  YOUR_TEXT must be surrounded by quotes"
    echo "   -t  --text"
    echo "              Text you want to turn to emojis."
    echo "   -e  --emoji"
    echo "              Emoji for creating characters."
    echo "   -s  --space"
    echo "              Emoji for spaces between characters."
    echo "              If no space is specified, the :blank: emoji is used."
    echo "   -h  --help  Output this help."
}

if [ $# -lt 2 ]; then
    usage
    exit 1
fi

#
# Parameter processing
#
text=""
while [[ $# > 0 ]]
do
key="$1"
shift
case $key in
    -t|--text)
    text=$1
    shift
    ;;
    -e|--emoji)
    emoji=$1
    shift
    ;;
    -s|--space)
    space=$1
    shift
    ;;
    *)
    echo "Unrecognized parameter(s): $*"
    usage
    exit 2
    ;;
esac
done

#
# Parameter checking
#
if [ "$text" == "" ]; then
    echo "Text not specified/"
    usage
    exit 3
else
    YOUR_TEXT=$text
fi

if [ "$emoji" == "" ]; then
    echo "Emoji not specified/"
    usage
    exit 3
else
    COLOR=":$emoji:"
fi

if [ "$space" == "" ]; then
    SPACE=":blank:"
else
    SPACE=":$space:"
fi


#YOUR_TEXT=$1
#COLOR=":$2:"
#SPACE=":$3:"

# Create an associative array of alphabet emoji conversions
declare -A ALPHABET
ALPHABET["a"]="$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE"
ALPHABET["b"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE"
ALPHABET["c"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["d"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE"
ALPHABET["e"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["f"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE"
ALPHABET["g"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE$SPACE\n$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$COLOR$SPACE"
ALPHABET["h"]="$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE"
ALPHABET["i"]="$COLOR$COLOR$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["j"]="$SPACE$SPACE$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE"
ALPHABET["k"]="$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE"
ALPHABET["l"]="$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["m"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE"
ALPHABET["n"]="$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE"
ALPHABET["o"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["p"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE"
ALPHABET["q"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE\n$SPACE$SPACE$COLOR$COLOR$SPACE"
ALPHABET["r"]="$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE$SPACE\n$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$COLOR$SPACE"
ALPHABET["s"]="$COLOR$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["t"]="$COLOR$COLOR$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$SPACE$COLOR$SPACE$SPACE"
ALPHABET["u"]="$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["v"]="$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE"
ALPHABET["w"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$COLOR$SPACE$COLOR$SPACE$COLOR$SPACE\n$COLOR$COLOR$SPACE$COLOR$COLOR$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE"
ALPHABET["x"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$COLOR$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE\n$SPACE$COLOR$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE"
ALPHABET["y"]="$COLOR$SPACE$SPACE$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$COLOR$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE\n$SPACE$SPACE$COLOR$SPACE$SPACE$SPACE"
ALPHABET["z"]="$COLOR$COLOR$COLOR$SPACE\n$SPACE$SPACE$COLOR$SPACE\n$SPACE$COLOR$SPACE$SPACE\n$COLOR$SPACE$SPACE$SPACE\n$COLOR$COLOR$COLOR$SPACE"
ALPHABET["."]="$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$COLOR$SPACE"
ALPHABET[","]="$SPACE$SPACE$SPACE\n$SPACE$SPACE$SPACE\n$SPACE$SPACE$SPACE\n$SPACE$COLOR$SPACE\n$COLOR$SPACE$SPACE"
ALPHABET["'"]="$COLOR$SPACE\n$COLOR$SPACE\n$SPACE$SPACE\n$SPACE$SPACE\n$SPACE$SPACE"
ALPHABET["!"]="$COLOR$SPACE\n$COLOR$SPACE\n$COLOR$SPACE\n$SPACE$SPACE\n$COLOR$SPACE"
ALPHABET[" "]="$SPACE\n$SPACE\n$SPACE\n$SPACE\n$SPACE"

#
# Actual execution
#
LOWER=${YOUR_TEXT,,}
echo "Paste this in slack \(^_^)/"
echo "==========================="
TEXT=""
for i in $(seq 0 $((${#LOWER} - 1))); do
	TEXT+="${ALPHABET[${LOWER:$i:1}]}\n"
done

LENGTH=$(printf $TEXT | wc -l)
LINE1=""
LINE2=""
LINE3=""
LINE4=""
LINE5=""
COUNTER=1

while [ $COUNTER -lt $(($LENGTH + 1)) ]; do
   if [ $(($(($COUNTER - 1)) % 5)) -eq 0 ]; then
      LINE1+=`printf $TEXT | awk 'NR == n {print; exit}' n=$COUNTER`
      COUNTER=$(($COUNTER + 1))
   elif [ $(($(($COUNTER - 2)) % 5)) -eq 0 ]; then
      LINE2+=`printf $TEXT | awk 'NR == n {print; exit}' n=$COUNTER`
      COUNTER=$(($COUNTER + 1))
   elif [ $(($(($COUNTER - 3)) % 5)) -eq 0 ]; then
      LINE3+=`printf $TEXT | awk 'NR == n {print; exit}' n=$COUNTER`
      COUNTER=$(($COUNTER + 1))
   elif [ $(($(($COUNTER - 4)) % 5)) -eq 0 ]; then
      LINE4+=`printf $TEXT | awk 'NR == n {print; exit}' n=$COUNTER`
      COUNTER=$(($COUNTER + 1))
   elif [ $(($(($COUNTER - 5)) % 5)) -eq 0 ]; then
      LINE5+=`printf $TEXT | awk 'NR == n {print; exit}' n=$COUNTER`
      COUNTER=$(($COUNTER + 1))
   else
      echo "Something's fucked ¯\_(ツ)_/¯"
   fi
done

FINAL="$LINE1\n$LINE2\n$LINE3\n$LINE4\n$LINE5\n"
printf $FINAL
echo "==========================="
